manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: qwerty22121998
      url-base: github.com/qwerty22121998
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-anim
      remote: qwerty22121998
      revision: main
  self:
    path: config
